config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :bookings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
   # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new

    @booking = Booking.new

  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user

    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

    private

    def booking_params
      params.require(:booking).permit(:user_id, :date, :start_time, :end_time)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bookings/index.html.erb
<div>
  <h1>See your bookings</h1>

    <% @bookings.each do |booking| %>
      <div class="margin-10">
      <div> <%= booking.date %></div>
      <div> <%= booking.start_time %></div>
      <div> <%= booking.end_time %></div>
          </div>
      <% end %>



</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1>Create a new booking</h1>
      <%= simple_form_for @booking do |f| %>
        <%= f.input :date, as: :date, html5: true, start_year: Date.today, end_year: Date.today.year + 1%>
        <%= f.input :start_time, as: :time, html5: true%>
        <%= f.input :end_time, as: :time, html5: true%>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>

    </div>

  </div>
</div>

app/views/bookings/show.html.erb
<div>
  <h1>This is your booking
  </h1>
</div>

<div>
  <p>Your booking on the <%= @booking.date%></p>

  <p>Starts at <%= @booking.start_time.strftime("%k:%M")%> and ends at <%= @booking.end_time.strftime("%k:%M")%></p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RtcBooking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
      <div >
      </div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div>
  <h1 class="text-center"> Welcome to RTC Booking center</h1>
  <h3 class="text-center"> <%= link_to "Book a Court", bookings_path%> </h3>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if current_page?(root_path) %>
      <style>
        .navbar-lewagon {
          background: transparent !important;
          position: absolute !important;
          width: 100% !important;

        }
        .navbar-lewagon a {
            color: white !important;
            text-decoration: none;
        }

        h1{
          color:white !important;
        }

      </style>
    <% end %>


<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <h1 style='font-family: Pacifico; color: #1BBC9A;'>cribnb</h1>
<% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
        </li>
        <li class="nav-item active">
          <%= link_to "Bookings", bookings_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="http://taysidereusers.co.uk/wp-content/plugins/all-in-one-seo-pack/images/default-user-image.png" />
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile",  edit_user_registration_path(current_user), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
        <!-- Nav if the user is not signed in -->
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>